name: Rover Image Fetch Image Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  BuildImage:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Create Meta Data
        id: metaraw
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/kiranviswanathb/roverapp
          tags: |
            type=semver,pattern={{version}}

      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.metaraw.outputs.tags }}
          labels: ${{ steps.metaraw.outputs.labels }}
          build-args: |
            BUILDKIT_CONTEXT_KEEP_GIT_DIR=true